services:

  java-app:
    build:
      context: .  # путь к директории с Dockerfile
      dockerfile: Dockerfile
    container_name: local_llm_rag
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ragdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      postgresql:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: no
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend

  ollama:
    image: ollama/ollama
    container_name: ollama
#    ports:
#      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
      ollama serve &
      sleep 2 &&
      ollama pull gemma3:4b-it-q4_K_M &&
      ollama pull mxbai-embed-large &&
      wait
      "
    restart: unless-stopped
    networks:
      - backend

  postgresql:
    image: ankane/pgvector:v0.5.0
    container_name: postgres_local_llm_rag
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
      PGPASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
#    ports:
#      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
#      - ./postgres/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -U postgres -d ragdb"
      interval: 2s
      timeout: 20s
      start_period: 10s
      retries: 10
    labels:
      amplicode.image: postgres
    networks:
      - backend

volumes:
  postgresql_data:
  ollama-data:

networks:
  backend:
    driver: bridge
