spring.application.name=local_llm_rag

spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.model=${OLLAMA_CHAT_MODEL}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.main.allow-circular-references=true

logging.level.org.springframework.ai.chat.client.advisor=DEBUG