-- Основная таблица чатов
CREATE TABLE IF NOT EXISTS chat (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    title      VARCHAR(255)
);

-- Таблица записей чата
CREATE TABLE IF NOT EXISTS chat_entry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6),
    role       VARCHAR(255)
    CONSTRAINT chat_entry_role_check
    CHECK ((role)::TEXT = ANY (ARRAY['USER'::CHARACTER VARYING, 'ASSISTANT'::CHARACTER VARYING]::TEXT[])),
    chat_id    BIGINT
    REFERENCES chat(id)
);